services:
  web:
    build: .
    container_name: pawfinder-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - PETS_DB_PATH=/data/pets.db
    volumes:
      - petsdata:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  petsdata:
