[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E203"]
exclude = ["tests/fixtures/*", ".venv", "__pycache__"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "double"

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203"]
per-file-ignores = ["__init__.py:F401"]
